@url = http://localhost:8080

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJQMiBBUEkiLCJzdWIiOiJhZG1pbiIsImV4cCI6MTczMTg4OTIyNX0.syAD4k21RNxgCm8o9I5VrUuoKuWeyu0_oe4kPgtIbTM

###
GET {{url}}/colaboradores
Authorization: Bearer {{token}}

###
GET {{url}}/colaboradores/2
Authorization: Bearer {{token}}

###
POST {{url}}/colaboradores
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nome": "Batata"
}

###
PUT {{url}}/colaboradores/2
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nome": "Batata 02"
}

###
DELETE {{url}}/colaboradores/1
Authorization: Bearer {{token}}